/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.ApplicantDirectory;
import Model.InsurancePlans;
import Model.VaccineL;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author divya
 */
public class ManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerJPanel
     */
   private JPanel userProcessContainer;
   private ApplicantDirectory dir;
   private InsurancePlans plan;
   private VaccineL vac1;
   
    public ManagerJPanel() {
        initComponents();
    }

    ManagerJPanel(JPanel userProcessContainer, ApplicantDirectory dir, InsurancePlans plan,VaccineL vac1) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.dir= dir;
       this.plan = plan;
       this.vac1=vac1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        manageBtn = new javax.swing.JButton();
        createInsuranceBtn = new javax.swing.JButton();
        manageInsuranceButton = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        addVaccination = new javax.swing.JButton();

        jButton1.setText("jButton1");

        createBtn.setText("Create Applicant");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        manageBtn.setText("Manage Applicant");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        createInsuranceBtn.setText("Create Insurance Plan");
        createInsuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInsuranceBtnActionPerformed(evt);
            }
        });

        manageInsuranceButton.setText("Add Vaccine for pet");
        manageInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInsuranceButtonActionPerformed(evt);
            }
        });

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        addVaccination.setText("Add Vaccination");
        addVaccination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccinationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(assignBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createInsuranceBtn)
                            .addComponent(manageInsuranceButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addVaccination)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(createInsuranceBtn)
                .addGap(18, 18, 18)
                .addComponent(manageInsuranceButton)
                .addGap(31, 31, 31)
                .addComponent(createBtn)
                .addGap(28, 28, 28)
                .addComponent(manageBtn)
                .addGap(38, 38, 38)
                .addComponent(addVaccination)
                .addGap(30, 30, 30)
                .addComponent(assignBtn)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
         CreateJPanel panel = new CreateJPanel(userProcessContainer,dir);
        userProcessContainer.add("CreateJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
         ManageApplicantJPanel panel = new ManageApplicantJPanel(userProcessContainer,dir);
        userProcessContainer.add("ManageApplicantJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        
         AssignJPanel panel = new AssignJPanel(userProcessContainer,dir,plan);
        userProcessContainer.add("AssignPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_assignBtnActionPerformed

    private void createInsuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInsuranceBtnActionPerformed
        // TODO add your handling code here:
          CatalogJPanel panel = new CatalogJPanel(userProcessContainer,plan);
        userProcessContainer.add("CatalogJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createInsuranceBtnActionPerformed

    private void manageInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInsuranceButtonActionPerformed
        // TODO add your handling code here:
         VaccineJPanel panel = new VaccineJPanel(userProcessContainer,vac1);
        userProcessContainer.add("VaccineJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInsuranceButtonActionPerformed

    private void addVaccinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccinationActionPerformed
        // TODO add your handling code here:
        AddVaccineJPanel panel = new AddVaccineJPanel(userProcessContainer,vac1);
        userProcessContainer.add("AddVaccineJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addVaccinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccination;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createInsuranceBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageBtn;
    private javax.swing.JButton manageInsuranceButton;
    // End of variables declaration//GEN-END:variables
}
