/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ui;
/**
 *
 * @author divya
 */
public class SAFrame extends javax.swing.JFrame {

    /**
     * Creates new form SAFrame
     */
    Main main;

    public SAFrame(Main main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonAddBranch = new javax.swing.JButton();
        jButtonAddBranch1 = new javax.swing.JButton();
        jButtonAddBranch2 = new javax.swing.JButton();
        jButBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelTitle.setText("System Admin");

        jButtonAddBranch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAddBranch.setText(" Branch");
        jButtonAddBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBranchActionPerformed(evt);
            }
        });

        jButtonAddBranch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAddBranch1.setText("Library");
        jButtonAddBranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBranch1ActionPerformed(evt);
            }
        });

        jButtonAddBranch2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAddBranch2.setText("Users");
        jButtonAddBranch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBranch2ActionPerformed(evt);
            }
        });

        jButBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButBack.setText("Back");
        jButBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButtonAddBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonAddBranch1)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButBack)
                            .addComponent(jButtonAddBranch2))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddBranch1)
                    .addComponent(jButtonAddBranch)
                    .addComponent(jButtonAddBranch2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jButBack)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBranchActionPerformed
        // TODO add your handling code here:
        BranchFrame bf = new BranchFrame(this);
        bf.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jButtonAddBranchActionPerformed

    private void jButBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jButBackActionPerformed

    private void jButtonAddBranch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBranch2ActionPerformed
        // TODO add your handling code here:
        if(Main.branch.getBranchID()!=0){
        UsersFrame uf = new UsersFrame(this);
        uf.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAddBranch2ActionPerformed

    private void jButtonAddBranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBranch1ActionPerformed
        // TODO add your handling code here:
        LibraryFrame lf = new LibraryFrame(this);
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAddBranch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAFrame(new Main()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButBack;
    private javax.swing.JButton jButtonAddBranch;
    private javax.swing.JButton jButtonAddBranch1;
    private javax.swing.JButton jButtonAddBranch2;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
