/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.ApplicantDirectory;
import Model.Business;
import Model.InsurancePlans;
import Model.Pet;
import Model.PlanDetail;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divya
 */
public class AssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignJPanel
     */
    DefaultTableModel tableModel;
    private Business business;
    private ApplicantDirectory dir;
    JPanel userProcessContainer;
    private PlanDetail plan1;
    private InsurancePlans plan;
     Applicant applicant;
    
     
    public AssignJPanel() {
        initComponents();
        
    }

    AssignJPanel(JPanel userProcessContainer, ApplicantDirectory dir, InsurancePlans plan,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dir=dir;
        this.plan=plan;
        this.plan1=plan1;
         this.tableModel= (DefaultTableModel) jTable1.getModel();
          this.business=business;
           populateDp();
        populate();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        assignBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet Name", "Insurance Plan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(assignBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(assignBtn)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        
        
//          PlanDetail plan1=(PlanDetail) jComboBox1.getSelectedItem();
//          int selectedRow= jTable1.getSelectedRow();
//            Pet a= (Pet) jTable1.getValueAt(selectedRow,0);
//            a.setPlan(plan1);
//            plan1.addPlanID(a);
//        
//        
//        populate();
//        
//        
        
        
        
        
        
        
                int iid = (int) jComboBox1.getSelectedItem();
       //find the insurance object from business class
             PlanDetail plan1=this.business.findInsurance(iid);
                //getting the applicatiant object to set his pet insurance
                int selectedRowIndex=jTable1.getSelectedRow();
                int plan =Integer.parseInt(jComboBox1.getSelectedItem().toString());
                jTable1.setValueAt(plan, selectedRowIndex, 1);
               // int id=Integer.parseInt(jTable1.getValueAt(selectedRowIndex, 0).toString());
               Applicant applicant = this.business.findApplicant(plan);                 
                this.applicant=applicant;
//               applicant.getPet().setPlan(plan1);
  //  setting the value of insurance to table
               DefaultTableModel model= (DefaultTableModel )jTable1.getModel();
               model.setValueAt(plan1.getPlanID(), selectedRowIndex, 1);
                JOptionPane.showMessageDialog(this, "Assigned!");
      populate();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
public void populateDp(){
       
//     ArrayList<PlanDetail> plan1 = this.business.getPlan().getPlanList();
      
jComboBox1.removeAllItems();
        
        for(PlanDetail d:this.plan.getPlanList()){
            jComboBox1.addItem(d.getPlanID());
        }





//     for(PlanDetail d:business.getPlan().getPlanList()){
//         jComboBox1.addItem(d.getPlanID());
//     }
//        }
}
        
public void populate()
{
    tableModel.setRowCount(0);
        
        for(Applicant o:this.dir.getApplicantList())
        {
            Object[] row= new Object[2];
            
            row[0]=o.getPet().getPetName();
           // row[1]=o.getPet().getPlan().getPlanID();
            
            
            tableModel.addRow(row);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
