 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Contact;
import Model.Person;
import Model.Recipe;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author divya
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
     private Boolean validate = false;
     
       private final JFileChooser openFileChooser;
       public CreateJPanel() {
         this.openFileChooser=new JFileChooser();
         initComponents();
        
    }

    CreateJPanel(Person person1) {
        
// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      this.person = person1; 
       this.openFileChooser=new JFileChooser();
        initComponents();
       
    }

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fFname = new javax.swing.JTextField();
        fUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fPhno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fEmailID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fRecipeName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fNoServings = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fDifficultylevel = new javax.swing.JTextField();
        fNoOfIngredients = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fCategoryOfFood = new javax.swing.JTextField();
        fDescription = new javax.swing.JTextField();
        fIsglutenfree = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fSavebutton = new javax.swing.JButton();
        imgpath = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        fLname = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Chef First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Chef Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        fFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFnameActionPerformed(evt);
            }
        });
        jPanel1.add(fFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 107, -1));
        jPanel1.add(fUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 107, -1));

        jLabel4.setText("Phno.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        jPanel1.add(fPhno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 111, -1));

        jLabel5.setText("Email ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));
        jPanel1.add(fEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 111, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 71, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Recipe Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 94, 31));

        jLabel8.setText("Recipe Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel1.add(fRecipeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 107, -1));

        jLabel9.setText("No. Of Servings");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(fNoServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 107, -1));

        jLabel10.setText("Is Gluten Free");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel11.setText("No. of Ingredients");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 299, -1, -1));

        jLabel13.setText("Difficulty Level");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel1.add(fDifficultylevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 107, -1));
        jPanel1.add(fNoOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));

        jLabel14.setText("Category of food");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel15.setText("Description");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 72, -1));

        fCategoryOfFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCategoryOfFoodActionPerformed(evt);
            }
        });
        jPanel1.add(fCategoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, -1));

        fDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fDescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(fDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, 60));
        jPanel1.add(fIsglutenfree, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 107, -1));

        jLabel16.setText("Img path");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 90, 28));

        fSavebutton.setText("Save");
        fSavebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSavebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(fSavebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 140, -1));
        jPanel1.add(imgpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 220, -1));

        lblimage.setText("image");
        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 90, 100));

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(browseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        fLname.setText("jTextField1");
        jPanel1.add(fLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fSavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSavebuttonActionPerformed
        // TODO add your handling code here:
    
        try{    
        String chefFirstName = fFname.getText();
        String chefLastName = fLname.getText();
        String userName = fUsername.getText();

        String  phno  = fPhno.getText();
        String EmailID = fEmailID.getText();

        String recipeName = fRecipeName.getText();
        int noOfServings = Integer.valueOf(fNoServings.getText());
        String isGlutenfree = fIsglutenfree.getText();
   
        float difficultyLevel = Float.valueOf(fDifficultylevel.getText());
        int noOfIng = Integer.valueOf(fNoOfIngredients.getText());
        String categoryOfFood = fCategoryOfFood.getText();
        String Description =fDescription.getText();
        String path = imgpath.getText();
        
        
           String Regexcell = "\\d{10}";
            String Regexemail = "^[\\w-\\.+]*[\\w-\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
            //String regGluten = "^[Yes|yes|No|no]$";
            String y = "yes";
            String n = "no";
            
            //String emailAddress = txtemail.getText();

            if(! phno.matches(Regexcell) ){
                JOptionPane.showMessageDialog(this, "Enter Valid phone  Number!");
               
            }
                else if(!EmailID.matches(Regexemail)){
                JOptionPane.showMessageDialog(this, "Enter Valid Email Address!");
                
                }
            else if(recipeName.equals("")){
            JOptionPane.showMessageDialog(null," Recipe name cannot be empty " );
          
            }
            else if(fIsglutenfree.equals(""))
             {
                  JOptionPane.showMessageDialog(null," yes or no values " );
              
             }
                 
            else if(fFname.getText().equals("")){
            JOptionPane.showMessageDialog(null," First name cannot be empty " );
           
            }
            else if(fLname.getText().equals("")){
            JOptionPane.showMessageDialog(null," Last name cannot be empty " );
           
            }
            else if(fUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null," User name cannot be empty " );
           
            }
            else if(fNoServings.getText().length() == 0){
            JOptionPane.showMessageDialog(null," Number of servings cannot be empty " );
           
            }
            else if(fDifficultylevel.getText().length() == 0){
            JOptionPane.showMessageDialog(null," Difficulty level cannot be empty " );
           
            }
            else if(fNoOfIngredients.getText().length()== 0){
            JOptionPane.showMessageDialog(null," no. of ingredients cannot be empty " );
           
            }
            else  if(fCategoryOfFood.getText().equals("")){
            JOptionPane.showMessageDialog(null," category of food cannot be empty " );
           
            }
             else  if(fDescription.getText().equals("")){
            JOptionPane.showMessageDialog(null," description  cannot be empty " );
           
            }
               else if (imgpath.getText().equals("")){
            JOptionPane.showMessageDialog(null," Get Image");
             
               }
               else{
        
        
        this.person.setcFname(chefFirstName);
        this.person.setcLname(chefLastName);
        this.person.setUsername(userName);
       ImageIcon Photo = new ImageIcon(imgpath.getText());
        Contact contact= this.person.getContact();
        contact.setPhno(phno);
        contact.setEmail(EmailID);

        Recipe recipe = this.person.getRecipe();
        recipe.setRecipeTitle(recipeName);
        recipe.setNoOfServings(noOfServings);
       if(isGlutenfree.equals("Yes"))
       {
            recipe.setIsGlutenFree(true);
        }
        else {
           recipe.setIsGlutenFree(false);
       }
        recipe.setCatOfFood(categoryOfFood);
        recipe.setDifficultyLevel(difficultyLevel);
        recipe.setNuOfIng(noOfIng);
        recipe.setDescription(Description);
        recipe.setPhoto(Photo);
         fSavebutton.setEnabled(true);
         JOptionPane.showMessageDialog(null, "Recipe details added");
               
     }      
        }
    catch(HeadlessException | NumberFormatException ex){
             JOptionPane.showMessageDialog(this, "Please check data and try again!");
            
      
    }//GEN-LAST:event_fSavebuttonActionPerformed
    }
    private void fCategoryOfFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCategoryOfFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCategoryOfFoodActionPerformed

    private void fDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fDescriptionActionPerformed

    private void fFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fFnameActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        
         FileNameExtensionFilter fnef= new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        JFileChooser browseImageFile= new JFileChooser();
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue==JFileChooser.APPROVE_OPTION){
            File selectedImageFile= browseImageFile.getSelectedFile();
            String selectedImagePath= selectedImageFile.getAbsolutePath();
            
            imgpath.setText(selectedImagePath);
            
            JOptionPane.showMessageDialog(null,selectedImagePath );
            
            ImageIcon i1=new ImageIcon(selectedImagePath);
           
            Image image=i1.getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
            lblimage.setIcon(new ImageIcon(image));
            
    }//GEN-LAST:event_browseBtnActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JTextField fCategoryOfFood;
    private javax.swing.JTextField fDescription;
    private javax.swing.JTextField fDifficultylevel;
    private javax.swing.JTextField fEmailID;
    private javax.swing.JTextField fFname;
    private javax.swing.JTextField fIsglutenfree;
    private javax.swing.JTextField fLname;
    private javax.swing.JTextField fNoOfIngredients;
    private javax.swing.JTextField fNoServings;
    private javax.swing.JTextField fPhno;
    private javax.swing.JTextField fRecipeName;
    private javax.swing.JButton fSavebutton;
    private javax.swing.JTextField fUsername;
    private javax.swing.JTextField imgpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimage;
    // End of variables declaration//GEN-END:variables
}
